object JC666Versions {
    const val android_gradle_plugin = "4.2.1"
    const val kotlin = "1.6.0"
    const val coroutines = "1.4.3"

    const val androidx_activity_ktx = "1.6.1"
    const val androidx_compose = "1.3.1"
    const val androidx_compose_compiler = "1.3.2"
    const val androidx_benchmark = "1.0.0"
    const val androidx_multidex = "2.0.1"
    const val androidx_appcompat = "1.3.0"
    const val androidx_biometric = "1.1.0"
    const val androidx_coordinator_layout = "1.1.0"
    const val androidx_constraint_layout = "2.0.4"
    const val androidx_preference = "1.1.1"
    const val androidx_legacy = "1.0.0"
    const val androidx_annotation = "1.5.0"
    const val androidx_lifecycle = "2.5.1"
    const val androidx_fragment = "1.5.1"
    const val androidx_navigation = "2.5.1"
    const val androidx_recyclerview = "1.2.1"
    const val androidx_core = "1.8.0"
    const val androidx_paging = "3.1.1"
    const val androidx_transition = "1.4.0"
    const val androidx_work = "2.7.1"
    const val androidx_datastore = "1.0.0"
    const val androidx_splashscreen = "1.0.0"
    const val androidx_viewpage2 = "1.0.0"
    const val google_material = "1.3.0"
    const val androidx_room = "2.4.2"
    const val google_firebase = "25.12.0"

    //third party library
    const val google_gson = "2.8.8"
    const val leakcanary = "2.10"
    const val database_sqlcipher = "4.4.3"
    const val sqlite = "2.0.1"
    const val android_xcrash = "3.0.0"
    const val zip4j = "2.9.0"
    const val bouncycastle_bcprov = "1.64"
    const val gkemon = "2.5"
    const val permissionx = "1.6.1"
    const val coil = "2.2.2"

    const val retrofit = "2.9.0"

    //unit test
    const val junit = "5.5.2"
    const val androidx_test_junit = "1.1.5"
    const val androidx_test_espresso = "3.3.0"
}

object JC666Dependencies {
    const val tools_androidgradle = "com.android.tools.build:gradle:${JC666Versions.android_gradle_plugin}"
    const val tools_kotlingradle = "org.jetbrains.kotlin:kotlin-gradle-plugin:${JC666Versions.kotlin}"
    const val tools_benchmarkgradle = "androidx.benchmark:benchmark-gradle-plugin:${JC666Versions.androidx_benchmark}"

    const val kotlin_stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${JC666Versions.kotlin}"
    const val kotlin_stdlib_jdk8 = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${JC666Versions.kotlin}"
    const val kotlin_reflect = "org.jetbrains.kotlin:kotlin-reflect:${JC666Versions.kotlin}"
    const val kotlin_coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${JC666Versions.coroutines}"
    const val kotlin_coroutines_test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${JC666Versions.coroutines}"
    const val kotlin_coroutines_android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${JC666Versions.coroutines}"
    const val kotlin_coroutines_android_jdk8 = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:${JC666Versions.coroutines}"

    const val androidx_compose_ui = "androidx.compose.ui:ui:${JC666Versions.androidx_compose}"
    const val androidx_compose_ui_test = "androidx.compose.ui:ui-test-junit4:${JC666Versions.androidx_compose}"
    const val androidx_compose_ui_test_manifest = "androidx.compose.ui:ui-test-manifest:${JC666Versions.androidx_compose}"
    const val androidx_compose_ui_tooling = "androidx.compose.ui:ui-tooling:${JC666Versions.androidx_compose}"
    const val androidx_compose_foundation = "androidx.compose.foundation:foundation:${JC666Versions.androidx_compose}"
    const val androidx_compose_material = "androidx.compose.material:material:${JC666Versions.androidx_compose}"
    const val androidx_annotation = "androidx.annotation:annotation:${JC666Versions.androidx_annotation}"
    const val androidx_benchmark_junit4 = "androidx.benchmark:benchmark-junit4:${JC666Versions.androidx_benchmark}"
    const val androidx_biometric = "androidx.biometric:biometric:${JC666Versions.androidx_biometric}"
    const val androidx_fragment_ktx = "androidx.fragment:fragment-ktx:${JC666Versions.androidx_fragment}"
    const val androidx_multidex = "androidx.multidex:multidex:${JC666Versions.androidx_multidex}"
    const val androidx_appcompat = "androidx.appcompat:appcompat:${JC666Versions.androidx_appcompat}"
    const val androidx_coordinatorlayout = "androidx.coordinatorlayout:coordinatorlayout:${JC666Versions.androidx_coordinator_layout}"
    const val androidx_constraintlayout = "androidx.constraintlayout:constraintlayout:${JC666Versions.androidx_constraint_layout}"
    const val androidx_legacy = "androidx.legacy:legacy-support-v4:${JC666Versions.androidx_legacy}"
    const val androidx_lifecycle_common = "androidx.lifecycle:lifecycle-common:${JC666Versions.androidx_lifecycle}"
    const val androidx_lifecycle_livedata = "androidx.lifecycle:lifecycle-livedata-ktx:${JC666Versions.androidx_lifecycle}"
    const val androidx_lifecycle_process = "androidx.lifecycle:lifecycle-process:${JC666Versions.androidx_lifecycle}"
    const val androidx_lifecycle_viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${JC666Versions.androidx_lifecycle}"
    const val androidx_lifecycle_runtime = "androidx.lifecycle:lifecycle-runtime-ktx:${JC666Versions.androidx_lifecycle}"
    const val androidx_paging = "androidx.paging:paging-runtime-ktx:${JC666Versions.androidx_paging}"
    const val androidx_preference = "androidx.preference:preference-ktx:${JC666Versions.androidx_preference}"
    const val androidx_safeargs = "androidx.navigation:navigation-safe-args-gradle-plugin:${JC666Versions.androidx_navigation}"
    const val androidx_navigation_fragment = "androidx.navigation:navigation-fragment-ktx:${JC666Versions.androidx_navigation}"
    const val androidx_navigation_ui = "androidx.navigation:navigation-ui:${JC666Versions.androidx_navigation}"
    const val androidx_recyclerview = "androidx.recyclerview:recyclerview:${JC666Versions.androidx_recyclerview}"
    const val androidx_core = "androidx.core:core:${JC666Versions.androidx_core}"
    const val androidx_core_ktx = "androidx.core:core-ktx:${JC666Versions.androidx_core}"
    const val androidx_transition = "androidx.transition:transition:${JC666Versions.androidx_transition}"
    const val androidx_work_ktx = "androidx.work:work-runtime-ktx:${JC666Versions.androidx_work}"
    const val androidx_work_testing = "androidx.work:work-testing:${JC666Versions.androidx_work}"
    const val androidx_datastore = "androidx.datastore:datastore:${JC666Versions.androidx_datastore}"
    const val androidx_splashscreen = "androidx.core:core-splashscreen:${JC666Versions.androidx_splashscreen}"
    const val androidx_viewpager2 = "androidx.viewpager2:viewpager2:${JC666Versions.androidx_viewpage2}"
    const val androidx_activity_ktx = "androidx.activity:activity-ktx:${JC666Versions.androidx_activity_ktx}"
    const val google_material = "com.google.android.material:material:${JC666Versions.google_material}"
    const val google_room_runtime = "androidx.room:room-runtime:${JC666Versions.androidx_room}"
    const val google_room_ktx = "androidx.room:room-ktx:${JC666Versions.androidx_room}"
    const val google_room_compiler = "androidx.room:room-compiler:${JC666Versions.androidx_room}"
    const val google_firebase_bom = "com.google.firebase:firebase-bom:${JC666Versions.google_firebase}"
    const val google_firebase_crashlytics_ktx = "com.google.firebase:firebase-crashlytics-ktx"
    const val google_firebase_crashlytics_ndk = "com.google.firebase:firebase-crashlytics-ndk"
    const val google_firebase_analytics_ktx = "com.google.firebase:firebase-analytics-ktx"
    const val google_firebase_perf_ktx = "com.google.firebase:firebase-perf-ktx"

    //third party library
    const val google_gson = "com.google.code.gson:gson:${JC666Versions.google_gson}"
    const val leakcanary = "com.squareup.leakcanary:leakcanary-android-core:${JC666Versions.leakcanary}"
    const val net_zetetic_database_sqlcipher = "net.zetetic:android-database-sqlcipher:${JC666Versions.database_sqlcipher}"
    const val androidx_sqlite = "androidx.sqlite:sqlite:${JC666Versions.sqlite}"
    const val iqiyi_xcrash_android = "com.iqiyi.xcrash:xcrash-android-lib:${JC666Versions.android_xcrash}"
    const val net_lingala_zip4j = "net.lingala.zip4j:zip4j:${JC666Versions.zip4j}"
    const val org_bouncycastle_bcprov = "org.bouncycastle:bcprov-jdk15on:${JC666Versions.bouncycastle_bcprov}"
    const val gkemon_xml_to_pdf_generator = "com.github.Gkemon:XML-to-PDF-generator:${JC666Versions.gkemon}"
    const val guolindev_permissionx = "com.guolindev.permissionx:permissionx:${JC666Versions.permissionx}"
    const val io_coil_kt = "io.coil-kt:coil:${JC666Versions.coil}"
    const val io_coil_kt_gif = "io.coil-kt:coil-gif:${JC666Versions.coil}"
    const val io_coil_kt_compose = "io.coil-kt:coil-compose:${JC666Versions.coil}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${JC666Versions.retrofit}"
    const val retrofit_gson = "com.squareup.retrofit2:converter-gson:${JC666Versions.retrofit}"


    //unit test
    const val junit = "junit:junit:${JC666Versions.junit}"
    const val androidx_junit = "androidx.test.ext:junit:${JC666Versions.androidx_test_junit}"
    const val androidx_test_extensions = "androidx.test.ext:junit-ktx:${JC666Versions.androidx_test_junit}"
    const val androidx_test_espresso_core = "androidx.test.espresso:espresso-core:${JC666Versions.androidx_test_espresso}"

}